
on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - uses: action/checkout@v3 
      - name: 'login' 
        run: docker login --username ${{secret.username}} --password ${{secret.password}}   

      - name: 'build image' 
        run: docker build -t ${{secret.username}}/my-image

      - name: 'push image' 
        run: docker push ${{secret.username}}/my-image