
on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - uses: actions/checkout@v3 
      - name: 'login' 
        run: docker login --username ${{ secrets.username }} --password ${{ secrets.password }}   

      - name: 'build image' 
        run: docker build -t ${{secrets.username}}/my-image .

      - name: 'push image' 
        run: docker push ${{secrets.username}}/my-image